inputs_def:
  - handle: image_file
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: output_dir
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - handle: water_mark
    json_schema:
      type: string
      ui:widget: text
    nullable: false
outputs_def:
  - handle: save_address
    description: Output
    json_schema:
      type: string
      ui:widget: file
  - handle: wm_shape
    json_schema:
      type: number
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Add Text Water Mark
icon: ":logos:python:"
